# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 19:31
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('active_zone_name', models.CharField(max_length=50, verbose_name='专区活动名称')),
                ('activity_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='活动描述')),
                ('order', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('is_shelf', models.BooleanField(choices=[(0, '上架'), (1, '下架')], default=0, verbose_name='是否上架')),
            ],
            options={
                'verbose_name': '首页专区活动信息管理',
                'verbose_name_plural': '首页专区活动信息管理',
                'db_table': 'activezone',
            },
        ),
        migrations.CreateModel(
            name='GoodsActiveZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('active_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.ActiveZone', verbose_name='专区活动ID')),
            ],
            options={
                'verbose_name': '首页专区活动商品管理表',
                'verbose_name_plural': '首页专区活动商品管理表',
                'db_table': 'goodsactivezone',
            },
        ),
        migrations.CreateModel(
            name='GoodsActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=100, verbose_name='活动名称')),
                ('image_address', models.ImageField(upload_to='user/%Y/%m/%d', verbose_name='图片地址')),
                ('url_address', models.CharField(max_length=200, verbose_name='路径')),
            ],
            options={
                'verbose_name': '首页活动信息管理',
                'verbose_name_plural': '首页活动信息管理',
                'db_table': 'broadcast',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('category_name', models.CharField(max_length=30, verbose_name='分类名称')),
                ('category_intro', models.CharField(blank=True, max_length=200, null=True, verbose_name='分类简介')),
            ],
            options={
                'verbose_name': '分类管理',
                'verbose_name_plural': '分类管理',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('image_address', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='图片地址')),
            ],
            options={
                'verbose_name': '图片信息管理',
                'verbose_name_plural': '图片信息管理',
                'db_table': 'goodsimage',
            },
        ),
        migrations.CreateModel(
            name='GoodsSkuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('goods_name', models.CharField(max_length=50, verbose_name='商品名')),
                ('goods_intro', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='商品简介')),
                ('goods_price', models.FloatField(verbose_name='商品价格')),
                ('goods_inventory', models.IntegerField(default=0, verbose_name='商品库存')),
                ('goods_sales', models.IntegerField(default=0, verbose_name='商品销量')),
                ('logo_address', models.ImageField(upload_to='goods/%Y/%m/%d', verbose_name='图片地址')),
                ('is_shelf', models.BooleanField(choices=[(0, '上架'), (1, '下架')], default=0, verbose_name='是否上架')),
                ('goods_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='分类ID')),
            ],
            options={
                'verbose_name': '商品信息管理',
                'verbose_name_plural': '商品信息管理',
                'db_table': 'goodsskuinfo',
            },
        ),
        migrations.CreateModel(
            name='GoodsSpuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_spu_name', models.CharField(max_length=20, verbose_name='商品名')),
                ('goods_spu_intro', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='商品简介')),
            ],
            options={
                'verbose_name': '商品SPU管理',
                'verbose_name_plural': '商品SPU管理',
                'db_table': 'spuinfo',
            },
        ),
        migrations.CreateModel(
            name='GoodsUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('unit_name', models.CharField(max_length=10, verbose_name='单位名')),
            ],
            options={
                'verbose_name': '商品单位管理',
                'verbose_name_plural': '商品单位管理',
                'db_table': 'goodsunit',
            },
        ),
        migrations.CreateModel(
            name='IndexImageBroadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('broadcast_name', models.CharField(max_length=100, verbose_name='轮播名称')),
                ('image_address', models.ImageField(upload_to='user/%Y%m/%d', verbose_name='图片地址')),
                ('order', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('goods_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsSkuInfo', verbose_name='商品ID')),
            ],
            options={
                'verbose_name': '首页轮播信息管理',
                'verbose_name_plural': '首页轮播信息管理',
                'db_table': 'broad',
            },
        ),
        migrations.AddField(
            model_name='goodsskuinfo',
            name='goods_spu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsSpuInfo', verbose_name='商品SPU_ID'),
        ),
        migrations.AddField(
            model_name='goodsskuinfo',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsUnit', verbose_name='商品单位ID'),
        ),
        migrations.AddField(
            model_name='goodsimage',
            name='goods_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsSkuInfo', verbose_name='商品SkU_ID'),
        ),
        migrations.AddField(
            model_name='goodsactivezone',
            name='goods_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsSkuInfo', verbose_name='商品ID'),
        ),
    ]
