# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20180816_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activezone',
            name='is_shelf',
            field=models.BooleanField(choices=[(1, '下架'), (0, '上架')], default=0, verbose_name='是否上架'),
        ),
        migrations.AlterField(
            model_name='goodsskuinfo',
            name='is_shelf',
            field=models.BooleanField(choices=[(1, '下架'), (0, '上架')], default=0, verbose_name='是否上架'),
        ),
    ]
